jxRequirements:
  autoUpdate:
    enabled: false
    schedule: ""
  bootConfigURL: https://github.com/jenkins-x/jx3-boot-config
  buildPacks:
    buildPackLibrary:
      gitRef: master
      gitURL: https://github.com/jenkins-x/jx3-pipeline-catalog.git
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-enhanced-prawn
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    namespace: jx
    project: "292032292180"
    provider: eks
    region: us-east-1
    registry: 292032292180.dkr.ecr.us-east-1.amazonaws.com
  environments:
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: dev
    owner: Silkworm3
    repository: Cluster
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: staging
  - ingress:
      domain: ""
      externalDNS: false
      namespaceSubDomain: ""
      tls:
        email: ""
        enabled: false
        production: false
    key: production
  gitops: true
  ingress:
    domain: aad3d3fac9c064944ba57bdd1649ce87-b8215846b1dcc3c0.elb.us-east-1.amazonaws.com
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  kaniko: true
  pipelineUser:
    username: KangoV
  repository: nexus
  secretStorage: vault
  storage:
    backup:
      enabled: false
      url: ""
    logs:
      enabled: true
      url: s3://logs-tf-jx-enhanced-prawn-20201113121645607700000006
    reports:
      enabled: true
      url: s3://reports-tf-jx-enhanced-prawn-20201113121645600200000001
    repository:
      enabled: true
      url: s3://repository-tf-jx-enhanced-prawn-20201113121645606100000004
  vault:
    aws:
      dynamoDBRegion: us-east-1
      dynamoDBTable: vault-unseal-tf-jx-enhanced-prawn-BShltlTQ
      kmsKeyId: b47619f1-4bed-4372-8efc-bf1fe18446f8
      kmsRegion: us-east-1
      s3Bucket: vault-unseal-tf-jx-enhanced-prawn-20201113121645604900000003
      s3Region: us-east-1
  velero:
    schedule: ""
    ttl: ""
  versionStream:
    ref: master
    url: https://github.com/jenkins-x/jxr-versions.git
  webhook: lighthouse
jxRequirementsIngressExternalDNS:
  enabled: false
jxRequirementsIngressTLS:
  enabled: false
jxRequirementsVault:
  enabled: true
