apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        Silkworm3/Cluster: true
        Silkworm3/project-3: true
        Silkworm3/project-4: true
        Silkworm3/project-5: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: false
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        Silkworm3/Cluster: merge
        Silkworm3/project-3: merge
        Silkworm3/project-4: merge
        Silkworm3/project-5: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - Silkworm3/Cluster
        - Silkworm3/project-3
        - Silkworm3/project-4
        - Silkworm3/project-5
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - Silkworm3/Cluster
        - Silkworm3/project-3
        - Silkworm3/project-4
        - Silkworm3/project-5
      target_url: http://dashboard-jx.jenkinsxhackathon.co.uk
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
