apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - Silkworm3/Cluster
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Silkworm3/project-3
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Silkworm3/project-4
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Silkworm3/project-5
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Silkworm3/project-6
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - Silkworm3/project-7
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      Silkworm3/Cluster:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Silkworm3/project-3:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Silkworm3/project-4:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Silkworm3/project-5:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Silkworm3/project-6:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      Silkworm3/project-7:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - Silkworm3/Cluster
      trusted_org: todo
    - repos:
      - Silkworm3/project-3
      trusted_org: todo
    - repos:
      - Silkworm3/project-4
      trusted_org: todo
    - repos:
      - Silkworm3/project-5
      trusted_org: todo
    - repos:
      - Silkworm3/project-6
      trusted_org: todo
    - repos:
      - Silkworm3/project-7
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
